### PR TITLE
[MRG] Circle ci integration

### PR DESCRIPTION
**Pull request by mrahim**
Trying to install spm as done by @lesteve on travis.

### CODE REVIEW

**Comment by lesteve** [comment]
Out of interest, have you tried running one of the examples as part of the tests on CircleCI? IIRC something was going wrong on Travis but I didn't have time to look at it in much detail.

**Comment by mrahim** [comment]
Here is an ouput of the build :
https://circleci.com/gh/mrahim/pypreprocess/119

**Comment by bthirion** [comment]
Great !

**Comment by dohmatob** [comment]
Cool. Waiting for dataset + output persistence, then we merge. ping @mrahim

**Comment by dohmatob** [comment]
BTW, the https://circleci.com/gh/mrahim/pypreprocess/135 says "Warning: circle.yml specified cache directory: /home/ubuntu/nilearn_data but it does not exist". Should we make -p``/home/ubuntu/nilearn_data`` at some point during the config ?

**Comment by mrahim** [comment]
The warning is related to the fact that `nilearn_data` was created in the auditory example during the test phase, then it was automatically removed and circle_ci was unable to reload it.
That's why I

**Comment by mrahim** [comment]
The warning is related to the fact that `nilearn_data` was created in the auditory example during the test phase, then it was automatically removed and circle_ci was unable to reload it.
That's why I added the auditory fetching as a python command line in the dependecies, so that `nilearn_data` will be cached before the test.

**Comment by dohmatob** [comment]
OK, merging. Great job!

**Pull request merged**
