### PR TITLE
Fixed unicode decode error. Closes #271

### LINKED ISSUE #271: UnicodeDecodeError
```
$ pip install -e .
Obtaining file:///D:/drive/workspace/pypreprocess
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\drive\workspace\pypreprocess\setup.py", line 11, in <module>
        LONG_DESCRIPTION = open('README.rst').read()
      File "C:\Users\filo\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 8437: character maps to <undefined>
```

### PR DESCRIPTION
**Pull request by chrisfilo**

### CODE REVIEW

**Comment by mrahim** [comment]
Thanks @chrisfilo. Tests are failing because ```enconding``` is specific to python3.

**Comment by chrisfilo** [comment]
Tests are failing due to #273

**Comment by bthirion** [comment]
LGTM.

**Comment by chrisfilo** [comment]
Tests are passing now.

**Comment by mrahim** [comment]
Merging, thanks !

**Pull request merged**
