### PR TITLE
Use a workaround to make reports work in Chrome browser.

### LINKED ISSUE #31: In report pages, thumbnails don't show in non-firefox browsers
In report pages, thumbnails don't show in non-firefox browsers

### PR DESCRIPTION
**Pull request by AlexandreAbraham**
Fix #31 

In order to load HTML code without using an iFrame, I load the html code in a javascript variable and use it in jQuery afterward. I kept the "html" extension of the files on purpose just to know that it is not proper JS code.

### CODE REVIEW

**Comment by bthirion** [comment]
That works. Maybe there should be somewhere a not restating what you said in the issue: As fallback, keep the jquery stuff but change the message to tell the user to run chromium-browser --allow-file-access-from-files, which works.

**Comment by dohmatob** [comment]
OK, looks great. I'll find time to take a closer look asap.

**Comment by dohmatob** [comment]
There is a small issue with the chrome hack. See [circle-ci](https://circle-artifacts.com/gh/neurospin/pypreprocess/92/artifacts/0/home/ubuntu/nilearn_data/fsl_feeds/pypreprocess_output/sub001/reports/report_preproc.html), and notice the unintented text floating around the generated thumbnails.

**Comment by dohmatob** [comment]
@AlexandreAbraham: Do you plan on working on this again, or have you abandoned it ?

**Comment by AlexandreAbraham** [comment]
I hqve been working on refreshing problem but I could not solve, this is still wip butvif you need to merge I can hurry

**Comment by AlexandreAbraham** [comment]
Rebased, should be mergeable after green. I stopped working on trying to make refreching more clever.

**Comment by bthirion** [comment]
LGTM.

**Comment by dohmatob** [comment]
This is not quite mergeable (yet). There is a major  unaddressed issue with the PR, namely a block of text dancing around the thumbnails (see my comments above).

Here:

circle-ci

**Pull request closed without merging**
