### PR TITLE
Reorganization of example directories

### PR DESCRIPTION
**Pull request by banilo**
Try to impose logical structure on the example set

Also tries to address  and #147

### CODE REVIEW

**Comment by dohmatob** [comment]
Cool. This is a start for the refactoring process. However, I'd instead create 3 subdirs as follows:

* easy_start/
* pure_python/
* advanced_pipelining/

Also, I'd modify the Readme accordingly.

**Comment by dohmatob** [comment]
Cool. You just have to rebase on upstream (neurospin/pypreprocess) master and we are done.

**Comment by AlexandreAbraham** [comment]
I know it's already merged but will "pure python" really be meaningful for the users? Maybe "no_dependency" would be better?

**Comment by dohmatob** [comment]
+1

On Sat, Aug 8, 2015 at 11:13 PM, Alexandre Abraham <notifications@github.com
> wrote:

> I know it's already merged but will "pure python" really be meaningful for
> the users? Maybe "no_dependency" would be better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurospin/pypreprocess/pull/156#issuecomment-129045420>
> .
>



-- 
DED

**Comment by dohmatob** [comment]
Bertrand: to which sentence does your question apply ?

6: We were unaware of the works of E.T Hale et al. on related
problems. Indeed, as the reviewer kindly points out, it would make
sense to link this work (especially the results obtained in section 4)
with ours.

XXX Bertrand: could you be more specific ?

1, 5: We will comb the manuscript for typos and confusing
notations. Thanks.


On Sun, Aug 9, 2015 at 10:42 AM, Elvis Dohmatob <gmdopp@gmail.com> wrote:

> +1
>
> On Sat, Aug 8, 2015 at 11:13 PM, Alexandre Abraham <
> notifications@github.com> wrote:
>
>> I know it's already merged but will "pure python" really be meaningful
>> for the users? Maybe "no_dependency" would be better?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/neurospin/pypreprocess/pull/156#issuecomment-129045420>
>> .
>>
>
>
>
> --
> DED
>



-- 
DED

**Pull request merged**
