### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by erramuzpe**
Added nilearn and matplotlib dependencies

### CODE REVIEW

**Comment by himito** [comment]
Also it's missing `configparser` for nipype.

**Comment by bthirion** [comment]
AFAIK the libxp6 problem is not realted to pypreprocess, is it ?

**Comment by himito** [comment]
No, it's related to the spm8 installation script. However, I was wrong, we find the deb package following the link, sorry.

**Comment by dohmatob** [comment]
Thanks.

**Pull request merged**
