### PR TITLE
Suggestion for pypreprocess logo

### PR DESCRIPTION
**Pull request by alpinho**

### CODE REVIEW

**Comment by dohmatob** [comment]
ok this is nice. Why do you use different fonts for the "py" and the "preprocess". Also the latter is all-caps.

**Comment by alpinho** [comment]
Py in a different font is to emphasize the "python" feature. I found small caps visually nicer for "preprocess" because the word looks more uniform. "Py" prefix is what I wanted to emphasize. I submitted the .xcf file. You can open it in gimp and write "preprocess" with regular capitalization and see how it looks like.

**Comment by alpinho** [comment]
When I said "the word looks more uniform", I meant the shape of the word.

**Comment by dohmatob** [comment]
Ok, i don't mind merging now, and then we'll enhance later. One last comment though: in your PR, you should replace the current logo `pypreprocess/reporting/images/logo.jpeg`, with your proposal.

Otherwise, LGTM!

**Comment by dohmatob** [comment]
OK, I'm merging and then fixing the issues raised above (which seem to have been ignored). Thanks.

**Pull request merged**
