### PR TITLE
Fixes issue #203: Users can configure location of cache and other temp files

### PR DESCRIPTION
**Pull request by dohmatob**

### CODE REVIEW

**Comment by bthirion** [comment]
I did not see any issue at first sight. I think that there needs to be some documentation of that behavior. For instance, as a first start, a comment in the .ini files that are provided and an example where the scratch dir is set arbitrarily.

**Comment by dohmatob** [comment]
On Fri, May 27, 2016 at 6:15 PM, bthirion <notifications@github.com> wrote:

> I did not see any issue at first sight. I think that there needs to be
> some documentation of that behavior. For instance, as a first start, a
> comment in the .ini files that are provided and
>
an example where the scratch dir is set arbitrarily.
>
the spm auditory example does this.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurospin/pypreprocess/pull/216#issuecomment-222189035>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAms1HFPLvbec9UkLXEup9X1kAOrymTZks5qFxiQgaJpZM4IoavJ>
> .
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by dohmatob** [comment]
On Fri, May 27, 2016 at 6:15 PM, bthirion <notifications@github.com> wrote:

> I did not see any issue at first sight. I think that there needs to be
> some documentation of that behavior. For instance, as a first start, a
> comment in the .ini files that are provided
>
and an example where the scratch dir is set arbitrarily.
>
the spm auditory example does this.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurospin/pypreprocess/pull/216#issuecomment-222189035>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAms1HFPLvbec9UkLXEup9X1kAOrymTZks5qFxiQgaJpZM4IoavJ>
> .
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by bthirion** [comment]
Sorry I did not see it. OK for merging.

**Comment by dohmatob** [comment]
OK, thanks for reviewing. Merging.

**Pull request merged**
