### PR TITLE
remove hard coded paths from realign and slice timing examples

### PR DESCRIPTION
**Pull request by jeromedockes**
about issue #157 
pure_python_preproc_demo.py doesn't work for me, I thought we should fix that before changing the paths.
In coreg_demo.py, I don't know what the paths in @dohmatob 's filesystem correspond to, if I download ABIDE using the nilearn fetcher the paths are different. Elvis, could we obtain the same files with the nilearn downloader?

### CODE REVIEW

**Comment by jeromedockes** [comment]
here is the output of pure_python_preproc_demo.py for me:

  170117-14:16:26,326 root INFO:
           Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
  170117-14:16:26,346 root INFO:
           Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
  2017-01-17 14:16:26,460:INFO: found SPM directory to be "/home/jerome/opt/spm8/spm8/spm8_mcr/spm8"
  2017-01-17 14:16:26,460:INFO: using SPM version: 8
  2017-01-17 14:16:26,460:INFO: setting SPM MCR path to "/home/jerome/opt/spm8/spm8.sh" and "use_mcr" to True
  2017-01-17 14:16:26,460:INFO: SPM configuration succeeded using SPM MCR.


         subject_data={}
         caching=True
         stc=True
         ref_slice=0
         interleaved=False
         slice_order=ascending
         realign=True
         coregister=True
         coreg_func_to_anat=True
         tsdiffana=True
         fwhm=None
         write_output_images=2
         concat=False
         report=True
         parent_results_gallery=None
         shutdown_reloaders=True
         reslice=True


  Traceback (most recent call last):
    File "./pure_python_preproc_demo.py", line 16, in <module>
      tsdiffana=True, realign=True, report=True, reslice=True)
    File "/home/jerome/.virtualenvs/py_2/local/lib/python2.7/site-packages/pypreprocess/purepython_preproc_utils.py", line 281, in do_subject_preproc
    n_sessions = len(subject_data.session_ids)
  TypeError: object of type 'NoneType' has no len()

**Comment by dohmatob** [comment]
@jeromedockes could you pleas rebase this so i can merge it. Thanks.

**Comment by jeromedockes** [comment]
the aforementionned issues with pure_python_pypreprocess_demo.py and coreg_demo.py remain

**Comment by dohmatob** [comment]
OK, LGTM. Merging. Will fix the error you report above in a separate PR.

**Pull request merged**
