### PR TITLE
BF: rmed zombie script

### PR DESCRIPTION
**Pull request by alpinho**
I removed the dummy file ssp_demo.py .

### CODE REVIEW

**Comment by eickenberg** [comment]
Cool! :)

**Comment by AlexandreAbraham** [comment]
Didn't even know that there were zombies in pypreprocess!

**Comment by dohmatob** [comment]
Beware of zombies. They're coming for you.

**Comment by dohmatob** [comment]
OK, PR moved to Dead-Valley @ middle-earth

**Pull request closed without merging**
