### PR TITLE
Fix: Failing due to deprecated colormap spectral

### PR DESCRIPTION
**Pull request by KamalakerDadi**
The newest release of matplotlib v2.2 removed the colormap spectral. This can be replaced by nipy_spectral. Otherwise, we have failures with processing output files.

Can I have reviews and merge ?

Thanks

### CODE REVIEW

**Comment by bthirion** [comment]
Great, thx!

**Comment by bthirion** [comment]
Actually, there is at least another occurrence in tsdiffana. Can you change it too ?

**Comment by KamalakerDadi** [comment]
>Actually, there is at least another occurrence in tsdiffana. Can you change it too ?

Can you post me the link ? You mean Travis or CircleCI ?

**Comment by bthirion** [comment]
Can be seen in Travis.

**Comment by KamalakerDadi** [comment]
I suspect that travis is failing with colormap 'spectral' because of nilearn version is 0.4.0. Both environments are 0.4.0 https://github.com/neurospin/pypreprocess/blob/master/.travis.yml

We fixed that issue in new release 0.4.1. Shall I change that in this PR ?

**Comment by bthirion** [comment]
Oops, you're right. Merging. We should upgrade the nilearn dependence to 0.4.1

**Pull request merged**
