### PR TITLE
BF: Removing spaces in output image names

### LINKED ISSUE #179: Output image names in reports  includes spaces
Which makes it difficult to (re-)use them

### PR DESCRIPTION
**Pull request by mrahim**
Fix #179

### CODE REVIEW

**Comment by bthirion** [comment]
LGTM. If there exist some tests for this module, an additional test would be great...

**Comment by mrahim** [comment]
AFAIK, there are no tests for `subject_data` module.
Should we open an issue about it ?

**Comment by bthirion** [comment]
No.


Sent from my smartphone. Sorry for misspelling and brevity.

-------- Message d'origine --------
De : mrahim <notifications@github.com> 
Date : 09/12/2015  11:30  (GMT+01:00) 
À : neurospin/pypreprocess <pypreprocess@noreply.github.com> 
Cc : bthirion <bertrand.thirion@inria.fr> 
Objet : Re: [pypreprocess] BF: Removing spaces in output image names (#180) 

AFAIK, there are no tests for subject_data module.

Should we open an issue about it ?

**Comment by bthirion** [comment]
The circleci failure is unrelated. Merging.

**Pull request merged**
