### PR TITLE
Added configuration for CircleCI 2.0

### PR DESCRIPTION
**Pull request by kchawla-pi**

### CODE REVIEW

**Comment by KamalakerDadi** [comment]
Should Close #308

**Comment by kchawla-pi** [comment]
@bthirion I believe I have transitioned the CircleCI config successfully. It is now the tests that are failing. Take a look and let me know.
CircleCI was broken for so long because the `/circle.yml` file currently in master is incomplete and missing many important commands which are present in the green builds.
At some point, someone pushed and merged a wrong file, causing subsequent builds to fail.

**Comment by bthirion** [comment]
OK. I propose that you remove the old config.yml, then we merge that one.
Thx !

**Comment by KamalakerDadi** [comment]
Nipype has dropped support related to nosetests and moved to pytest. Hence, Nipype related tests in CircleCI are failing. I am not sure from which Nipype version they have dropped this support.

Travis is happy because we are running tests with Nipype 0.13.0.

Either we could force CircleCI to install 0.13.0 or latest version whichever supports running nose ?

**Comment by kchawla-pi** [comment]
Pytest supports running nose tests. Can we not simply replace the command
nose with pytest?

**Comment by KamalakerDadi** [comment]
Nipype moving to pytest
https://github.com/nipy/nipype/blob/37f3781a4f765a7793d17389cd959d2eb4fcd617/doc/changelog/0.X.X-changelog#L145

I don't know much about pytest.

**Comment by kchawla-pi** [comment]
We can downgrade Nina bel and associated packages for now, while working to transition to pytest. 
We plan to move to pytest  for nilearn and nistats, this can be a good pilot for that.
I have some familiarity with pytest. I'll try my hand on this one.

**Comment by bthirion** [comment]
Can you simply switch nosetest -> pytest ?

**Comment by kchawla-pi** [comment]
I think we can replace the command 'nose' with 'pytest' and pytest will run
them no problem.

On Sep 2, 2018 21:55, "bthirion" <notifications@github.com> wrote:

Can you simply switch nosetest -> pytest ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/neurospin/pypreprocess/pull/309#issuecomment-417955717>,
or mute the thread

**Comment by kchawla-pi** [comment]
I would like to do this myself tomorrow, a good way to get started with
examining the tests in detail.

**Comment by bthirion** [comment]
Great, thx.
B

**Comment by kchawla-pi** [comment]
Travis is failing because it couldn't find a fie in /tmp/ . Might be spurious error Someone rerun this.

**Comment by kchawla-pi** [comment]
There are some aspects that are missing here and have been improved in #310 . We either merge both of these or I will transfer some. ALso there are conflicts between path for SPM8 and SPM12. We should talk and resolve those.

**Comment by bthirion** [comment]
But there should not be any SPM8 involved. Currently, we only support SPM12.

**Pull request merged**
