### PR TITLE
Circleci fix

### PR DESCRIPTION
**Pull request by swaythe**
Travis build completes again. Circle CI build fails due to an SPM-related permission error. Looking into it now.

### CODE REVIEW

**Comment by bthirion** [comment]
Travis is broken again due to a matplotlib import problem. 
Can you check that ?

**Comment by swaythe** [comment]
> My understanding is that you're not addressing yet the CircleCI issue.
> 
> Yet LGTM overall.

I have been addressing the CircleCI issues, but new ones keep cropping up so it's ongoing. :~) 

Travis builds again - the matplotlib import error is now resolved.

**Comment by bthirion** [comment]
OK, should we merge that one before proceeding to the next one ?

**Comment by swaythe** [comment]
> OK, should we merge that one before proceeding to the next one ?

Yeah, that works.

**Comment by bthirion** [comment]
Merging.

**Comment by swaythe** [comment]
Great, thanks!

**Pull request merged**
